// SPDX-License-Identifier: MIT OR Apache-2.0
//
// The auction quote, against a reference written in another language.
//
// `mul_div_floor` and `mul_div_ceil` are lifted from the sibling `antumbra-lez`
// crate and carry their own differential vectors there. What has none until now
// is the *composition* this file covers: the discount multiplier, the two
// clamps, and the re-strike that fires when the lot rather than the target runs
// out. That is not an arbitrary choice of target — it is where a real defect
// lived. Before the re-strike, a bid of 4,000 against a lot worth 2,368 was
// charged the whole 4,000 and the auction reported its target fully raised,
// hiding the shortfall a debt auction exists to clear.
//
// The vectors are generated by `tests/gen_auction_vectors.py`, in Python's
// arbitrary-precision integers. CI regenerates them and diffs byte for byte, so
// the file cannot drift from the oracle that produced it.

use antumbra_auction::{Auction, AuctionError, DiscountSchedule, Rounding};

const VECTORS: &str = include_str!("vectors/quote.txt");

fn kind(e: AuctionError) -> &'static str {
    match e {
        AuctionError::Overflow => "Overflow",
        AuctionError::DivideByZero => "DivideByZero",
        AuctionError::DiscountOutOfRange => "DiscountOutOfRange",
        AuctionError::NothingLeftToSell => "NothingLeftToSell",
        AuctionError::BidNotAnImprovement => "BidNotAnImprovement",
    }
}

#[test]
fn every_vector_from_the_python_oracle_reproduces() {
    let mut checked = 0usize;
    let mut refusals = 0usize;
    for (n, line) in VECTORS.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (lhs, rhs) = line.split_once('|').unwrap_or_else(|| {
            panic!(
                "line {}: no ' | ' separating inputs from expectation",
                n + 1
            )
        });
        let a: Vec<u128> = lhs
            .split_whitespace()
            .map(|t| {
                t.parse()
                    .unwrap_or_else(|_| panic!("line {}: {} is not a u128", n + 1, t))
            })
            .collect();
        assert_eq!(a.len(), 8, "line {}: expected 8 inputs", n + 1);
        let auction = Auction {
            collateral_left: a[3],
            to_raise: a[4],
            schedule: DiscountSchedule {
                min: a[0],
                max: a[1],
                window: a[2] as u64,
            },
        };
        let got = auction.quote_with(a[5], a[6], a[7] as u64, Rounding::Down);

        let want: Vec<&str> = rhs.split_whitespace().collect();
        match (&got, want.as_slice()) {
            (Ok(f), [m, p, o]) => {
                assert_eq!(f.multiplier.to_string(), *m, "line {}: multiplier", n + 1);
                assert_eq!(f.paid.to_string(), *p, "line {}: paid", n + 1);
                assert_eq!(
                    f.collateral_out.to_string(),
                    *o,
                    "line {}: collateral_out",
                    n + 1
                );
            }
            (Err(e), [name]) => {
                assert_eq!(kind(*e), *name, "line {}: refusal kind", n + 1);
                refusals += 1;
            }
            (Ok(f), [name]) => panic!(
                "line {}: the oracle refuses with {}, this quotes paid={} out={}",
                n + 1,
                name,
                f.paid,
                f.collateral_out
            ),
            (Err(e), _) => panic!(
                "line {}: the oracle quotes a fill, this refuses with {}",
                n + 1,
                kind(*e)
            ),
            (Ok(_), other) => panic!(
                "line {}: the expectation has {} field(s), which is neither a fill nor a refusal",
                n + 1,
                other.len()
            ),
        }
        checked += 1;
    }
    // A vector file that shrank to nothing, or to refusals only, would pass every
    // assertion above and prove nothing. Both floors are deliberate.
    assert!(checked >= 3000, "only {} vector(s) were checked", checked);
    assert!(
        refusals >= 100 && checked - refusals >= 2000,
        "{} refusal(s) and {} fill(s): the file has lost one of its two halves",
        refusals,
        checked - refusals
    );
}
